- name: Configure Compute Instance
  hosts: 
    - all
  become: yes
  gather_facts: no

  vars:
    packages: 
        - openjdk-11-jre
  
  vars_files:
    - .gcp.env.yaml

  tasks:
   - name: Add user, append to groups
     user:
       name: hadoop
       shell: /bin/bash
       groups: google-sudoers,adm
       append: yes
   - name: install packages
     apt:
       name: "{{ packages }}"
       state: latest
       update_cache: yes
   - name: Create an ext4 filesystem on /dev/sdb and check disk blocks
     filesystem:
       fstype: ext4
       dev: /dev/sdb
   - name: Mount and bind /dev/sdb volume
     mount:
       path: /data
       src: /dev/sdb
       state: mounted
       fstype: ext4 
   - name: Change ownership and group
     file:
       path: /data
       state: directory
       recurse: yes
       owner: hadoop
       group: hadoop

- name: Load Bug-Fixes
  include: bug-fix.yaml

  
