- name: Fundamental Compute Instance Configurations
  hosts: 
    - all
  become: yes
  gather_facts: no

  # vars:
    # general:
    #   project: sandbox-236618
    #   region: europe-west4
    #   auth_kind: serviceaccount
    #   service_account_file: ~/.ssh/ansible.json
    # scopes:
    #   - https://www.googleapis.com/auth/compute

    # packages: 
    #     - openjdk-8-jre
    #     - openjdk-8-jdk-headless
    #     - pdsh

    # user: 
    #     hadoop:                               #username: Such as hadoop, elasticsearch etc.. Apply to other 
    #         type: "rsa"                       #
    #         file: "/home/hadoop/.ssh/id_rsa"  #username!
    #         groups: "google-sudoers,adm"

    # additional_disks:
    #     data-disk: 
    #         path: "/data"
    #         device: "/dev/sdb"
    #         fstype: "ext4"
    #         owner: "hadoop"                   #username!
    #     log-disk: 
    #         path: "/logs"
    #         device: "/dev/sdc"
    #         fstype: "ext4"
    #         owner: "hadoop"                   #username!


  # tasks:
  
  roles:
    #run w/ default var values
    - role: tansudasli.gcp_basic_configurations 


  
