- name: Fundamental Compute Instance Configurations
  hosts: 
    - all
  become: yes
  gather_facts: no

  # tasks:
  
  roles:

    - role: tansudasli.gcp_basic_configurations 
      packages: 
        - openjdk-8-jre
        - openjdk-8-jdk-headless
        - pdsh

      user: 
          hadoop:                               #username: Such as hadoop, elasticsearch etc.. Apply to other 
              type: "rsa"                       #
              file: "/home/hadoop/.ssh/id_rsa"  #username!
              groups: "google-sudoers,adm"

      additional_disks:
          data-disk: 
              path: "/data"
              device: "/dev/sdb"
              fstype: "ext4"
              owner: "hadoop"                   #username!
          log-disk: 
              path: "/logs"
              device: "/dev/sdc"
              fstype: "ext4"
              owner: "hadoop"                   #username!

    - role: tansudasli.gcp_basic_installations
      installation:
        xxx:                                    #username!
          src: "https://ftp.itu.edu.tr/Mirror/Apache/hadoop/common/hadoop-3.2.1/hadoop-3.2.1.tar.gz"
          dest: "/"                             #tool extraction path 


  
