- name: Fundamental Compute Instance Configurations
  hosts: 
    - all
  become: yes
  gather_facts: no

  vars:
    packages: 
        - openjdk-8-jre
        - openjdk-8-jdk-headless
        - pdsh
    additional_disks:
        data-disk: 
            path: "/data"
            device: "/dev/sdb"
            fstype: "ext4"
            owner: "hadoop"
        log-disk: 
            path: "/logs"
            device: "/dev/sdc"
            fstype: "ext4"
            owner: "hadoop"

  
  vars_files:
    - .gcp.env.yaml

  tasks:
   - name: Add machine user as sudoers
     user:
       name: hadoop
       shell: /bin/bash
       groups: google-sudoers,adm
       append: yes
   - name: Install packages
     apt:
       name: "{{ packages }}"
       state: latest
       update_cache: yes
   - name: Format additional-disks' filesystem
     filesystem:
       fstype: "{{ item.value.fstype }}"
       dev: "{{ item.value.device }}"
     with_dict: "{{ additional_disks }}"
   - name: Mount and bind additional-disks
     mount:
       path: "{{ item.value.path }}"
       src: "{{ item.value.device }}"
       state: mounted
       fstype: "{{ item.value.fstype }}"
     with_dict: "{{ additional_disks }}" 
   - name: Change additional-disks' ownership
     file:
       path: "{{ item.value.path }}"
       state: directory
       recurse: yes
       owner: "{{ item.value.owner }}"
       group: "{{ item.value.group }}"
     with_dict: "{{ additional_disks }}"  


   
- name: Load Bug-Fixes
  include: bug-fix.yaml

  
