- name: Configure Compute Instance
  hosts: 
    - all
  become: yes
  gather_facts: no

  vars:
    packages: 
        - openjdk-11-jre
  
  vars_files:
    - .gcp.env.yaml


  tasks:
   - name: install packages
     apt:
       name: "{{ packages }}"
       state: latest
       update_cache: yes

  # sudo df -h, after mount 
  # sudo fdisk -l  , before mount
   - name: Create an ext4 filesystem on /dev/sdb1 and check disk blocks
     filesystem:
       fstype: ext4
       dev: /dev/sdb
       opts: -cc  
  
      

# - name: Manage new instances
#   hosts: new_instances
#   connection: ssh
#   sudo: True
#   roles:
#     - base_configuration
#     - production_server