- name: Create Compute Instance
  hosts: localhost
  gather_facts: no
  
  vars_files:
    - .gcp.env.yaml

  tasks:
   - name: create a boot-disk
     gcp_compute_disk:
         name: 'boot-disk-01'
         size_gb: 100
         source_image: 'projects/ubuntu-os-cloud/global/images/family/ubuntu-2004-lts'
         zone: "{{ zone }}"
         project: "{{ project }}"
         auth_kind: "{{ auth_kind }}"
         service_account_file: "{{ service_account_file }}"
         scopes: "{{ scopes }}"
         state: present
     register: bootdisk
   - name: create data-disk
     gcp_compute_disk:
         name: 'data-disk-01'
         size_gb: 300
         zone: "{{ zone }}"
         project: "{{ project }}"
         auth_kind: "{{ auth_kind }}"
         service_account_file: "{{ service_account_file }}"
         scopes: "{{ scopes }}"
         state: present
     register: datadisk
   - name: create log-disk
     gcp_compute_disk:
         name: 'log-disk-01'
         size_gb: 300
         zone: "{{ zone }}"
         project: "{{ project }}"
         auth_kind: "{{ auth_kind }}"
         service_account_file: "{{ service_account_file }}"
         scopes: "{{ scopes }}"
         state: present
     register: logdisk     
   - name: create a static-IP address
     gcp_compute_address:
         state: present
         name: "{{ ip_name }}"
         region: "{{ region }}"
         project: "{{ project }}"
         auth_kind: "{{ auth_kind }}"
         service_account_file: "{{ service_account_file }}"
         scopes: "{{ scopes }}"
     register: address
   - name: create an instance
     gcp_compute_instance:
         state: present
         name: instance-01
         machine_type: f1-micro
         disks:
           - auto_delete: true
             boot: true
             source: "{{ bootdisk }}"
           - auto_delete: true
             boot: false
             source: "{{ datadisk }}"
           - auto_delete: true
             boot: false
             source: "{{ logdisk }}"             
         network_interfaces:
             - access_configs:
               - name: 'test-ip-01'
                 nat_ip: "{{ address }}"
                 type: 'ONE_TO_ONE_NAT'
         zone: "{{ zone }}"
         project: "{{ project }}"
         auth_kind: "{{ auth_kind }}"
         service_account_file: "{{ service_account_file }}"
         scopes: "{{ scopes }}"
     register: instance


# tests
   - name: check SSH connection
     wait_for: host={{ address.address }} port=22 delay=10 timeout=60
