- name: Create Compute Instance
  hosts: localhost
  gather_facts: no

  vars:
    project: sandbox-236618
    region: us-west1
    zone: us-west1-a
    auth_kind: serviceaccount
    service_account_file: ~/.ssh/ansible-sandbox-236618-5fd34807ceb2.json
    network: default
    server_count: 
      - 1
      - 2
    instance_name: instance-
    scopes:
        - https://www.googleapis.com/auth/compute

  tasks:
    - name: create "{{ server_count }}" static-IP address
      gcp_compute_address:
        name: "{{ instance_name }}{{ item }}"
        project: "{{ project }}"
        region: "{{ region }}"
        auth_kind: "{{ auth_kind }}"
        service_account_file: "{{ service_account_file }}"
        scopes: "{{ scopes }}"
        state: present
      register: address
      with_items: "{{ server_count }}"

      # to access register value when it has more values!
      # it is so clear and concise w/ loop:
      # also, replace shell w/ debug module!
    - name: access address values
      shell: echo '"{{ item.address }}"' >> output
      loop: "{{ address.results }}"


