- name: Create Compute Instance
  hosts: localhost
  gather_facts: no

  vars:
    server_count: 
      - 1
      - 2


  tasks:

    # makes list below:
    # [['alice', 'ali'], ['alice', 'veli'], ['bob', 'ali'], ['bob', 'veli']]
    - name: access complex values
      debug: 
        msg: "{{ item[0] }} with index {{ ansible_loop.index }} = {{ ansible_loop.allitems[0:2] }}"
      loop: "{{ ['alice', 'bob'] | product(['ali', 'veli']) | list }}"
      loop_control:
        index_var: my_idx
        extended: yes

